# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  tiktok:
    image: tiktok:latest
    build: ./
    volumes:
      - "./tiktok:/app"
      - ".env:/app/.env"
    profiles: ["exclude-from-up"]

 
