# 作品(视频或图集)、直播、合集、音乐集合、个人主页的分享链接或者电脑浏览器网址
# (删除文案, 保证只有URL, https://v.douyin.com/kcvMpuN/ 或者 https://www.douyin.com/开头的)
# 可以设置多个链接, 确保至少一个链接
# 必选
link:
  - https://www.youtube.com/@kym-yydk
  - https://www.youtube.com/@sunkemito
  


#指定视频logo位置 rightbottom，righttop，lefttop，leftbottom,empty
logops:
  - righttop
  - empty

address_ip: 43.159.41.149

# 必选
path: /root/video_download/youtube

#最大并行 worker 数量
num_works: 1

#指定输出格式 可选值 "infer" | "mp4" | "mkv" | "mov"
output_format: mp4

# 存放子路径模板
subpath_template: \%\(channel\)s_\%\(channel_id\)s/\%\(upload_date>%Y-%m-%d\)s/\%\(title\)s.\%\(ext\)s

#临时下载的视频保存位置
temp_dir : /root/video_download/temp_video